---
repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95  # v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
          # https://github.com/pre-commit/pre-commit-hooks/issues/273
          - "--unsafe"
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args:
          - "--branch"
          - "main"
      - id: trailing-whitespace

  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e  # v8.30.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: e72a3ca1632f0b11a07d171449fe447a7ff6795e  # v0.48.0
    hooks:
      - id: markdownlint
        args:
          - -c
          - .markdownlint.yaml
          - --fix
          - --rules
          - sentences-per-line
        additional_dependencies:
          - sentences-per-line

  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a  # v2.4.2
    hooks:
      - id: codespell

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: ea2eb407b4cbce87cf0d502f36578950494f5ac9  # v1.23.1
    hooks:
      - id: zizmor
